In [175]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

In [204]:
train = pd.read_csv("C:/Users/OWUSU/Desktop/ML n DL/kaggle/train.csv",header=0)

In [205]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [206]:
del train["Cabin"]

In [212]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [208]:
train["Age"].fillna(train["Age"].median(),inplace=True)

In [209]:
train["Embarked"].fillna(train["Embarked"].value_counts().idxmax,inplace=True)

In [211]:
del train['Name']
del train['PassengerId']
del train['Ticket']

In [213]:
train = pd.get_dummies(train,drop_first=True)

In [214]:
train.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_C  \
0         0       3  22.0      1      0   7.2500         1           0   
1         1       1  38.0      1      0  71.2833         0           1   
2         1       3  26.0      0      0   7.9250         0           0   
3         1       1  35.0      1      0  53.1000         0           0   
4         0       3  35.0      0      0   8.0500         1           0   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [215]:
train.corr()

Survived    Pclass       Age     SibSp     Parch      Fare  \
Survived    1.000000 -0.338481 -0.064910 -0.035322  0.081629  0.257307   
Pclass     -0.338481  1.000000 -0.339898  0.083081  0.018443 -0.549500   
Age        -0.064910 -0.339898  1.000000 -0.233296 -0.172482  0.096688   
SibSp      -0.035322  0.083081 -0.233296  1.000000  0.414838  0.159651   
Parch       0.081629  0.018443 -0.172482  0.414838  1.000000  0.216225   
Fare        0.257307 -0.549500  0.096688  0.159651  0.216225  1.000000   
Sex_male   -0.543351  0.131900  0.081163 -0.114631 -0.245489 -0.182333   
Embarked_C  0.168240 -0.243292  0.030248 -0.059528 -0.011069  0.269335   
Embarked_Q  0.003650  0.221009 -0.031415 -0.026354 -0.081228 -0.117216   
Embarked_S -0.155660  0.081720 -0.014665  0.070941  0.063036 -0.166603   

            Sex_male  Embarked_C  Embarked_Q  Embarked_S  
Survived   -0.543351    0.168240    0.003650   -0.155660  
Pclass      0.131900   -0.243292    0.221009    0.081720  
Age         0.081163    0.030248   -0.031415   -0.014665  
SibSp      -0.114631   -0.059528   -0.026354    0.070941  
Parch      -0.245489   -0.011069   -0.081228    0.063036  
Fare       -0.182333    0.269335   -0.117216   -0.166603  
Sex_male    1.000000   -0.082853   -0.074115    0.125722  
Embarked_C -0.082853    1.000000   -0.148258   -0.778359  
Embarked_Q -0.074115   -0.148258    1.000000   -0.496624  
Embarked_S  0.125722   -0.778359   -0.496624    1.000000

In [220]:
uv = np.percentile(train.Fare,[99])[0]

In [221]:
uv

249.00622000000035

In [222]:
train[(train.Fare>uv)]

Survived  Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_C  \
27          0       1  19.0      3      2  263.0000         1           0   
88          1       1  23.0      3      2  263.0000         0           0   
258         1       1  35.0      0      0  512.3292         0           1   
311         1       1  18.0      2      2  262.3750         0           1   
341         1       1  24.0      3      2  263.0000         0           0   
438         0       1  64.0      1      4  263.0000         1           0   
679         1       1  36.0      0      1  512.3292         1           1   
737         1       1  35.0      0      0  512.3292         1           1   
742         1       1  21.0      2      2  262.3750         0           1   

     Embarked_Q  Embarked_S  
27            0           1  
88            0           1  
258           0           0  
311           0           0  
341           0           1  
438           0           1  
679           0           0  
737           0           0  
742           0           0

In [223]:
train.Fare[(train.Fare>3*uv)] = 3*uv

C:\Users\OWUSU\AppData\Local\Temp\ipykernel_8180\580088843.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.Fare[(train.Fare>3*uv)] = 3*uv


In [224]:
y = train["Survived"]

In [226]:
x = train.loc[:,train.columns!='Survived']

In [228]:
from sklearn.model_selection import train_test_split

In [229]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=0)

In [231]:
import xgboost as xgb

C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [234]:
xgb_clf = xgb.XGBClassifier(max_depth=5,n_estimators=1000,learning_rate=0.3,n_jobs=-1)

In [235]:
xgb_clf.fit(x_train,y_train)

[15:19:37] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.3, max_delta_step=0,
              max_depth=5, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=1000, n_jobs=-1,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [236]:
accuracy_score = (y_test,xgb_clf.predict(x_test))

In [237]:
accuracy_score

(495    0
 648    0
 278    0
 31     1
 255    1
       ..
 627    1
 380    1
 483    1
 516    1
 505    0
 Name: Survived, Length: 90, dtype: int64,
 array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1], dtype=int64))

In [241]:
from sklearn.model_selection import cross_val_score

In [242]:
accuracy_score = cross_val_score(xgb_clf,x,y,scoring='accuracy',cv=5)

C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[15:27:53] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[15:27:56] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[15:27:58] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[15:28:00] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\OWUSU\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[15:28:02] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [245]:
100*(accuracy_score.mean())

80.69738246186681

In [246]:
y_pred = xgb_clf.predict(x_test)

In [247]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1], dtype=int64)

In [248]:
y_pred_train = xgb_clf.predict(x_train)
y_pred_train

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [252]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [257]:
confusion_matrix(y_test,y_pred)

array([[45,  6],
       [10, 29]], dtype=int64)

In [258]:
confusion_matrix(y_train,y_pred_train)

array([[490,   8],
       [ 12, 291]], dtype=int64)

In [316]:
test = pd.read_csv("C:/Users/OWUSU/Desktop/ML n DL/kaggle/test.csv",header=0)

In [317]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [318]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [319]:
test["Embarked"].value_counts()

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [320]:
del test["Cabin"]
del test['Name']
del test["Ticket"]

In [326]:
del test['PassengerId']

In [327]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      418 non-null    int64  
 1   Sex         418 non-null    object 
 2   Age         418 non-null    float64
 3   SibSp       418 non-null    int64  
 4   Parch       418 non-null    int64  
 5   Fare        418 non-null    float64
 6   Embarked_C  418 non-null    uint8  
 7   Embarked_Q  418 non-null    uint8  
 8   Embarked_S  418 non-null    uint8  
dtypes: float64(2), int64(3), object(1), uint8(3)
memory usage: 20.9+ KB


In [322]:
test['Age'].fillna(test['Age'].median(),inplace=True)

In [323]:
test['Fare'].fillna(test['Fare'].median(),inplace=True)

In [324]:
test =  pd.get_dummies(test,columns=["Embarked"],drop_first=False)

In [331]:
test.head()

Pclass   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  Embarked_S  \
0       3  34.5      0      0   7.8292           0           1           0   
1       3  47.0      1      0   7.0000           0           0           1   
2       2  62.0      0      0   9.6875           0           1           0   
3       3  27.0      0      0   8.6625           0           0           1   
4       3  22.0      1      1  12.2875           0           0           1   

   Sex_male  
0         1  
1         0  
2         1  
3         1  
4         0

In [330]:
test = pd.get_dummies(test,columns=["Sex"],drop_first=True)

In [332]:
y_pred_new = xgb_clf.predict(test)
y_pred_new


array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [334]:
test.shape

(418, 9)

In [338]:
y_train_new = y_train.iloc[:418,]

In [339]:
y_train_new.shape

(418,)

In [341]:
test_new =pd.read_csv("C:/Users/OWUSU/Desktop/ML n DL/kaggle/test.csv",header=0)

In [342]:
PassengerId = test_new["PassengerId"]

In [343]:
Survived = y_pred_new

TypeError: Cannot construct a dtype from an array

In [347]:
result = pd.DataFrame({'PassengerId':PassengerId,'Survived':Survived})

In [348]:
print(result)

     PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         1
..           ...       ...
413         1305         1
414         1306         1
415         1307         0
416         1308         1
417         1309         0

[418 rows x 2 columns]


In [355]:
print(final_result)

,PassengerId,Survived
0,892,0
1,893,0
2,894,1
3,895,1
4,896,1
5,897,0
6,898,0
7,899,1
8,900,0
9,901,0
10,902,1
11,903,1
12,904,1
13,905,1
14,906,1
15,907,0
16,908,1
17,909,0
18,910,1
19,911,0
20,912,0
21,913,0
22,914,1
23,915,0
24,916,0
25,917,0
26,918,0
27,919,0
28,920,1
29,921,0
30,922,1
31,923,1
32,924,1
33,925,0
34,926,0
35,927,0
36,928,1
37,929,0
38,930,0
39,931,1
40,932,0
41,933,1
42,934,0
43,935,1
44,936,1
45,937,0
46,938,0
47,939,1
48,940,0
49,941,1
50,942,1
51,943,0
52,944,1
53,945,1
54,946,0
55,947,0
56,948,0
57,949,0
58,950,0
59,951,1
60,952,1
61,953,1
62,954,0
63,955,1
64,956,0
65,957,1
66,958,1
67,959,1
68,960,0
69,961,1
70,962,1
71,963,0
72,964,1
73,965,0
74,966,1
75,967,1
76,968,1
77,969,1
78,970,1
79,971,1
80,972,1
81,973,1
82,974,1
83,975,1
84,976,1
85,977,0
86,978,1
87,979,1
88,980,1
89,981,1
90,982,0
91,983,1
92,984,1
93,985,1
94,986,0
95,987,0
96,988,1
97,989,1
98,990,1
99,991,0
100,992,0
101,993,1
102,994,1
103,995,1
104,996,0
105,997,1
106,998,1
107,999,1
108,1000

In [356]:
result.to_csv(r'C:\Users\OWUSU\Desktop\ML n DL\kaggle\result.csv')